name: Run Tests and Deploy Vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo-latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run e2e tests
        run: yarn test:e2e
        env:
          ENV: ${{ vars.ENV_GH }}
          MONGO_CONNECTION_URI: ${{ secrets.MONGO_CONNECTION_URI }}
          MONGO_CONNECTION_URI_FOR_TESTS: ${{ secrets.MONGO_CONNECTION_URI_FOR_TESTS }}
          PORT: ${{ vars.PORT }}
          SECRET: ${{ secrets.SECRET }}
          ACCESS_TOKEN_EXPIRATION_LIVE: ${{ secrets.ACCESS_TOKEN_EXPIRATION_LIVE }}
          REFRESH_TOKEN_EXPIRATION_LIVE: ${{ secrets.REFRESH_TOKEN_EXPIRATION_LIVE }}

      - name: Run integration tests
        run: yarn test:integration
#
#  deploy:
#    name: Deploy
#    needs: tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions